version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    # container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # container_name: mongo-express
    environment:
      # ME_CONFIG_MONGODB_URL: "mongodb://admin:pass@mongo:27017/"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      # ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_OPTIONS_EDITORTHEME: default
    depends_on:
      - mongodb